[package]
name = "gin-rummy-desktop"
version = "1.0.0"
description = "Portable Windows shell for Gin Rummy Online"
authors = ["Choi0619"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gin_rummy_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3" }

[dependencies]
tauri = { version = "2.11.3" }
