-- Global, server-authoritative AI match statistics.
-- Run this once in the Supabase SQL editor, then configure the Render-only
-- SUPABASE_SERVICE_ROLE_KEY environment variable.

create table if not exists public.ai_global_stats (
  difficulty text primary key check (difficulty in ('easy', 'normal', 'hard')),
  player_wins bigint not null default 0,
  ai_wins bigint not null default 0,
  ties bigint not null default 0,
  total_games bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_match_history (
  id bigint generated by default as identity primary key,
  match_id uuid not null unique,
  player_id uuid references public.profiles(id) on delete set null,
  player_game_id text not null,
  player_name text not null,
  player_char text not null default '',
  difficulty text not null check (difficulty in ('easy', 'normal', 'hard')),
  player_result text not null check (player_result in ('win', 'lose', 'tie')),
  player_score integer not null check (player_score >= 0),
  ai_score integer not null check (ai_score >= 0),
  game_mode text not null default 'classic',
  target_score integer,
  created_at timestamptz not null default now()
);

create index if not exists ai_match_history_difficulty_created_idx
  on public.ai_match_history (difficulty, created_at desc);
create index if not exists ai_match_history_player_created_idx
  on public.ai_match_history (player_id, created_at desc);

insert into public.ai_global_stats (difficulty)
values ('easy'), ('normal'), ('hard')
on conflict (difficulty) do nothing;

alter table public.ai_global_stats enable row level security;
alter table public.ai_match_history enable row level security;

drop policy if exists "AI stats are publicly readable" on public.ai_global_stats;
create policy "AI stats are publicly readable"
  on public.ai_global_stats for select to anon, authenticated using (true);

drop policy if exists "AI match history is publicly readable" on public.ai_match_history;
create policy "AI match history is publicly readable"
  on public.ai_match_history for select to anon, authenticated using (true);

grant select on public.ai_global_stats to anon, authenticated;
revoke select on public.ai_match_history from anon, authenticated;
grant select (
  player_game_id, player_name, player_char, difficulty, player_result,
  player_score, ai_score, game_mode, target_score, created_at
) on public.ai_match_history to anon, authenticated;
revoke insert, update, delete on public.ai_global_stats from anon, authenticated;
revoke insert, update, delete on public.ai_match_history from anon, authenticated;

create or replace function public.record_ai_match(
  p_match_id uuid,
  p_player_id uuid,
  p_player_game_id text,
  p_player_name text,
  p_player_char text,
  p_difficulty text,
  p_player_result text,
  p_player_score integer,
  p_ai_score integer,
  p_game_mode text,
  p_target_score integer
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer;
begin
  if p_difficulty not in ('easy', 'normal', 'hard') then
    raise exception 'Invalid AI difficulty';
  end if;
  if p_player_result not in ('win', 'lose', 'tie') then
    raise exception 'Invalid AI match result';
  end if;

  insert into public.ai_match_history (
    match_id, player_id, player_game_id, player_name, player_char,
    difficulty, player_result, player_score, ai_score, game_mode, target_score
  ) values (
    p_match_id, p_player_id, coalesce(p_player_game_id, ''),
    coalesce(p_player_name, 'Player'), coalesce(p_player_char, ''),
    p_difficulty, p_player_result, greatest(p_player_score, 0),
    greatest(p_ai_score, 0), coalesce(p_game_mode, 'classic'), p_target_score
  )
  on conflict (match_id) do nothing;

  get diagnostics inserted_count = row_count;
  if inserted_count = 0 then
    return false;
  end if;

  insert into public.ai_global_stats (
    difficulty, player_wins, ai_wins, ties, total_games, updated_at
  ) values (
    p_difficulty,
    case when p_player_result = 'win' then 1 else 0 end,
    case when p_player_result = 'lose' then 1 else 0 end,
    case when p_player_result = 'tie' then 1 else 0 end,
    1,
    now()
  )
  on conflict (difficulty) do update set
    player_wins = ai_global_stats.player_wins + excluded.player_wins,
    ai_wins = ai_global_stats.ai_wins + excluded.ai_wins,
    ties = ai_global_stats.ties + excluded.ties,
    total_games = ai_global_stats.total_games + 1,
    updated_at = now();

  return true;
end;
$$;

revoke all on function public.record_ai_match(
  uuid, uuid, text, text, text, text, text, integer, integer, text, integer
) from public, anon, authenticated;
grant execute on function public.record_ai_match(
  uuid, uuid, text, text, text, text, text, integer, integer, text, integer
) to service_role;
